### ISSUE TITLE
样本标注到5000条NVD@Desc

### ISSUE THREAD

**Issue by xjtuncy** [Im-Asher/seed#2]

**Comment by Im-Asher** [comment]
#7 
Desc datasaet size is increased to 2k

**Comment by Im-Asher** [comment]
#11 added new labal VENDOR

**Comment by Im-Asher** [comment]
#13 Desc datasaet size is increased to 3k

**Comment by Im-Asher** [comment]
#19 increased the size of dataset to 4k
